services:
  - type: web
    name: chiru-mlbb-api
    env: node
    plan: free
    rootDir: server
    buildCommand: npm install
    startCommand: node server.js
    healthCheckPath: /health
    autoDeploy: true

  - type: static
    name: chiru-mlbb-store
    rootDir: client
    staticPublishPath: .